# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-30 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '账号表'},
        ),
    ]
